added crud, controllers, apis and services
Nezhit/liquibaseflyway pull request #1
Opened 2024-04-20 09:02 UTC by Nezhit

2024-04-23 09:20 UTC, Java-dummy58 requested changes

2024-04-23 09:20 UTC, FridayNight58 commented on pom.xml
> +		<!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
Лучше такие комментарии удаляй

2024-04-23 09:20 UTC, FridayNight58 commented on src/main/java/com/example/migrations/controllers/CustomerController.java
> +    public ResponseEntity<?> createCustomer(@RequestBody CustomerDto customerDto) {
`@RequestBody` и прочие аннотации должны быть описаны в параметрах метода в интерфейсе, а тут должно быть просто
`public ResponseEntity<?> createCustomer(CustomerDto customerDto) {`

2024-04-23 09:20 UTC, FridayNight58 commented on src/main/java/com/example/migrations/controllers/CustomerController.java
> +    public ResponseEntity<?> deleteCustomer(@PathVariable Long id) {
C `@PathVariable` такая же история

2024-04-23 09:20 UTC, FridayNight58 commented on src/main/java/com/example/migrations/controllers/CustomerController.java
> +    public ResponseEntity<?> getCustomers() {
Это што за прикол? Зачем тебе `ResponseEntity<?>` в рест контроллере. Почитай, чем отличается аннотация `@Controller` от `@RestController` и сделай, чтобы у тебя тут возвращался `List<Customer>`. В остальных местах тоже всё поправь

2024-04-23 09:20 UTC, FridayNight58 commented on src/main/java/com/example/migrations/controllers/CustomerController.java
> +    public ResponseEntity<?> updateCustomer(@RequestBody CustomerDto customerDto) {
А тут возвращай `Cusomer`

2024-04-23 09:20 UTC, FridayNight58 commented on src/main/java/com/example/migrations/controllers/EmployeeController.java
> +        return null;
Это што?

2024-04-23 09:20 UTC, FridayNight58 commented on src/main/java/com/example/migrations/controllers/MainController.java
> +        return "JOME";
Это что за класс? Зачем он нужен? Что за JOME?

2024-04-23 09:20 UTC, FridayNight58 commented on src/main/java/com/example/migrations/controllers/OrderController.java
> +
Пустая строка лишняя

2024-04-23 09:20 UTC, FridayNight58 commented on src/main/java/com/example/migrations/controllers/api/CustomerApi.java
> +
Удали пустую строку

2024-04-23 09:20 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/api/CustomerApi.java
> +    @GetMapping("/api/getCustomers")
У тебя неправильно сделан Rest api. В rest api мы работаем с ресурсами. Во-первых должен быть путь `/api/customers/`. Во-вторых нужно вешать над самим интерфейсом аннотацию `@RequestMapping("/api/customers")`. В этом случае над методом будет достаточно повесить просто аннотацию `@GetMapping`. В-третьих если в Rest api больше одного слова рядом, то должно быть не `/oneTwo/`, как в имени переменной, а `/one-two/`.

2024-04-23 09:20 UTC, FridayNight58 commented on src/main/java/com/example/migrations/controllers/api/CustomerApi.java
> +    public ResponseEntity<?>createCustomer(@RequestBody CustomerDto customerDto);
Где пробел? перед `createCustomer`? Не забывай использовать аннотацию ctrl+alt+l

2024-04-23 09:20 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/api/CustomerApi.java
> +    @DeleteMapping("/api/deleteCustomer/{id}")
Между методами делай пустую строку

2024-04-23 09:20 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/api/ProducerApi.java
> +
Это что за пустота?

2024-04-23 09:20 UTC, FridayNight58 commented on src/main/java/com/example/migrations/dto/CustomerDto.java
> +    private String phone;
Если у параметров дто нет аннотаций, то лучше не делай пустые строки. Но они у тебя появятся со свагггером

2024-04-23 09:20 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/dto/EmployeeDto.java
> +import java.time.LocalDate;
Это что такое?) Почему тут перед импортом пустая строка, так ещё и импорт слипся с аннотацией Getter

2024-04-23 09:20 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/dto/OrderDto.java
> +import java.time.LocalDate;
Такая же фигня

2024-04-23 09:20 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/entity/Customer.java
>  import jakarta.persistence.*;
Избавляйся везде от импортов со звёздочками

2024-04-23 09:20 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/entity/Employee.java
>  import java.time.LocalDate;
Пустую строку убери

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/CustomerApi.java
> +@RestController
Аннотация @RestController должна быть в реализующей классе, а не интерфейсе

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/CustomerApi.java
> +@RequestMapping("api/customer")
Сделай /api/customer

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/api_impl/CustomerController.java
> +
Удаляй пустую строку

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/api_impl/CustomerController.java
> +
Тоже пустая строка, удаляй

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/api_impl/CustomerController.java
> +    public Customer createCustomer( CustomerDto customerDto) {
Что это за пробел тут и в других методах? Следи за код стайлом и не забывай использовать ctrl+alt+l

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/api_impl/CustomerController.java
> +
Удаляй вот эту пустую строку тут и в основных местах

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/api_impl/MainController.java
> +public class MainController {
Что это за контроллер и для чего он нужен? Если ни для чего, то удаляй его

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/api_impl/OrderController.java
> +
Пустая строка

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/api_impl/ProducerController.java
> +
Строка пустая

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/dto/CustomerDto.java
> +
Удаляй пустую строку, так как в остальных классах её нет перед параметрами

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/entity/Customer.java
>  import jakarta.persistence.*;
Всё ещё актуально

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/entity/Customer.java
> +    public Customer(Long id, String title, String address, String phone) {
Почему тут два конструктора? Не совсем понимаю

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/entity/Employee.java
>  import jakarta.persistence.*;
Фикси звёздочку

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/entity/Good.java
>      @Column(name = "id_good")
Сделай все Primary Key (которые целочисленные) просто id, а не так, как тут

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/service/CustomerService.java
> +        System.out.println(customerDto.toString());
Зачем это тут? Убирай, тестируй через точку остановки либо так, но удаляй перед коммитом

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/service/CustomerService.java
> +        Customer customer = new Customer(customerDto.getTitle(), customerDto.getAddress(), customerDto.getPhone());
Сделай лучше так, чтобы в конструкторе Customer принимался CustomerDto, из которого бы всё и доставалось

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/service/CustomerService.java
> +        Customer customer = customerRepo.findById(id).orElse(null);
Перепиши на orElseThrow

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/service/CustomerService.java
> +        return customer;
Возвращай здесь не customer, а результат customerRepo.save(customer)

2024-04-29 18:38 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/service/CustomerService.java
> +        return customer;
Delelte операция не должна возвращать ничего, это void

2024-05-02 12:14 UTC, FridayNight58 commented on src/main/java/com/example/migrations/config/SwaggerConfig.java
> +public class SwaggerConfig {
Это откуда взялось? Сваггер вообще никак не должен появится в этом пулл реквесте. Весь сваггер будет в следующем пулле, это удаляй

2024-05-02 12:14 UTC, FridayNight58 commented on src/main/java/com/example/migrations/controllers/CustomerApi.java
> +
Пустая строка

2024-05-02 12:14 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/api_impl/CustomerController.java
> +
Всё ещё актуально

2024-05-02 12:14 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/entity/Customer.java
> +    public Customer(String title, String address, String phone) {
Этот конструктор используется или нет?

2024-05-02 12:14 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/entity/Employee.java
пустая строка

2024-05-02 12:14 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/entity/Order.java
> +
пустая строка

2024-05-02 12:14 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/service/CustomerService.java
> +        if (customerDto.getTitle() == null || customerDto.getAddress() == null || customerDto.getPhone() == null) {
Во всех дто, где нужно, добавь аннотации из библиотеки javax.validation, такие как @notnull, например. Почитай, разберись и исправь, чтобы вот таких ненужных проверок не было. Заодно протестируй, что будет, если передать null поле, которое помечается, как @notnull

2024-05-03 07:50 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/CustomerApi.java
> +    public Customer createCustomer(@RequestBody CustomerDto customerDto);
Вот тут ещё одна правка нужна, чтобы потом это не фиксить - CustomerDto назови CustomerCreateDto, а в апишках замени (как тут) Customer и прочий возврат сущностей на какой-нибудь CustomerRsDto. Возвращать напрямую сущности считается не лучшей практикой, так как сущность это про одно, а Dto про другое. Плюсом к этому появляются иногда поля в сущностях, которые не нужно возвращать, например как пароль в сущности пользователя

2024-05-03 07:50 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/dto/CustomerDto.java
> +    private Long id;
Стоп, а почему у тебя в DTO для создание сущности передается id? Откуда он тут возьмется? Его сгенерируют только когда сущность сохранится в БД

2024-05-03 07:50 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/dto/CustomerUpdateDto.java
> +    private Long id;
Зачем тут id тоже?

2024-05-03 07:50 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/dto/CustomerUpdateDto.java
> +@Setter
А зачем здесь сеттеры нужны?

2024-05-03 07:50 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/dto/EmployeeUpdateDto.java
> +
Пустая строка

2024-05-03 07:50 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/service/CustomerService.java
> +        if (customerDto.getTitle() == null || customerDto.getAddress() == null || customerDto.getPhone() == null) {
Всё ещё актуально

2024-05-03 07:50 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/service/CustomerService.java
> +        if(customerUpdateDto.getAddress()!=null) customer.setAddress(customerUpdateDto.getAddress());
getAddress() != null

2024-05-03 07:50 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/service/CustomerService.java
> +        return customerRepo.findById(id).get();
А если покупателя с таким id нет, то что?

2024-05-03 07:50 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/service/CustomerService.java
> +        Customer customer = customerRepo.findById(id).get();
А если нет с таким id?

2024-05-03 11:30 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/CustomerApi.java
> +    public List<Customer> getCustomers();
Нужно CustomerRsDto

2024-05-03 11:30 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/EmployeeApi.java
> +    public List<Employee> getEmployees();
EmployeeRsDto

2024-05-03 11:30 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/controllers/api_impl/OrderController.java
> +
пустая строка

2024-05-03 11:30 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/dto/CustomerCreateDto.java
> +@NoArgsConstructor
Теститл без @NoArgsConstructor?

2024-05-03 11:30 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/dto/CustomerUpdateDto.java
> +    @Override
Добавь пустую строку перед @Override

2024-05-03 11:30 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/dto/EmployeeRsDto.java
> +
Удаляй пустую строку

2024-05-03 11:30 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/dto/OrderRsDto.java
> +
пустая строка

2024-05-03 11:30 UTC, Java-dummy58 commented on src/main/java/com/example/migrations/dto/OrderUpdateDto.java
> +
пустая строка

2024-05-03 12:53 UTC, merged